apiVersion: v1
kind: Namespace
metadata:
  name: argo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argo
  source:
    repoURL: https://github.com/argoproj/argo-workflows
    targetRevision: v3.2.8
    path: manifests/cluster-install
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true